FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY mock_receiver.py .
COPY payload_parser.py .

RUN mkdir /uploads

ENV FLASK_APP=mock_receiver.py
ENV FLASK_RUN_HOST=0.0.0.0
# ENV FLASK_ENV=development # Enables debug mode if needed

EXPOSE 5000

CMD ["flask", "run"]