version: "3.9"
services:
  joern:
    image: ghcr.io/joernio/joern:nightly
    working_dir: /project
    volumes:
      - ./:/project
      - ./export:/export
    environment:
      _JAVA_OPTS: "-Xmx4g"
    entrypoint:
      - bash
      - -c
      - |
        set -euxo pipefail

        echo "INFO: Starting Joern processing..."
        echo "INFO: Current directory: $(pwd)"

        echo "INFO: Parsing codebase in /project to cpg.bin..."
        joern-parse . --output cpg.bin
        echo "INFO: Successfully created /project/cpg.bin"

        mkdir -p /export
        echo "INFO: Export directory /export ensured."

        echo "INFO: Exporting entire CPG (repr=all) to GraphSON at /export/cpg_all"
        joern-export cpg.bin --repr=all --format=graphson --out="/export/cpg_all"
        echo "INFO: Exported entire CPG successfully to /export/cpg_all."

        echo "INFO: All exports complete."
    restart: "no"

  lint:
    image: docker.io/pmdcode/pmd:latest
    working_dir: /project
    volumes:
      - ./:/project:ro
      - ./export/lint:/export/lint
    entrypoint:
      - bash
      - -e
      - -u
      - -x
      - -o
      - pipefail
      - -c
      - |
        echo "INFO: Running PMD linter on /project…"
        mkdir -p /export/lint

        pmd check \
          -d /project \
          -R category/java/bestpractices.xml,category/java/errorprone.xml,category/java/performance.xml,category/java/security.xml \
          -f json \
          -r /export/lint/pmd_report.json

        echo "INFO: PMD JSON written to /export/lint/pmd_report.json"
    depends_on:
      - joern
    restart: "no"
