services:

  github-bot:
    build: ./github-bot
    env_file:
      - ./github-bot.env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - msf-network
    restart: on-failure

  smee-client:
    image: node:18-alpine
    restart: unless-stopped 
    command: >
      sh -c "npm install --global smee-client && 
             smee -u https://smee.io/MQFI8eHvKVJBzDD8 -t http://github-bot:3000/webhook"
    networks:
      - msf-network
    depends_on:
      - github-bot

networks:
  msf-network:
    driver: bridge

volumes:
  ollama: {}
