services:
  postgres:
    container_name: db
    image: postgres:16.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - utask:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db -h localhost" ]
      interval: 2s
      timeout: 1s
      retries: 5
  liquibase:
    image: liquibase/liquibase:4.26-alpine
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/classpath
    command: [
      "--url=jdbc:postgresql://db:5432/db?autoReconnect=true&amp&allowPublicKeyRetrieval=true&amp&useSSL=false",
      "--username=user",
      "--password=password",
      "--classpath=/liquibase/classpath/",
      "--changeLogFile=changelog-master.yaml",
      "--secure-parsing=false",
      "--logLevel=info",
      "update"
    ]

volumes:
  utask:

